"""Imaging primitives. numpy and Pillow only — imports nothing web (invariant 2)."""

from .align import align, estimate_shift, residual, shift_image
from .colour import apply_gain_offset, fit_gain_offset, normalise
from .composite import (
    CompositeInvariantError,
    assert_outside_unchanged,
    composite,
    feather_mask,
    outside_difference,
)
from .derivatives import (
    GALLERY_EDGE,
    VIEWER_EDGE,
    Derivative,
    RegionPlan,
    RegionResult,
    apply_region_edit,
    build_pyramid,
    choose_best,
    plan_region_edit,
    to_array,
    to_png,
)
from .export import (
    DEFAULT_TOLERANCE,
    FLAT_BACKGROUND_SPREAD,
    Exported,
    background_mask,
    background_spread,
    encode,
    export,
    has_flat_background,
    make_transparent,
    upscale,
)
from .gutters import (
    Rect,
    column_flatness,
    expand_to_legal,
    flat_runs,
    gutter_fraction,
    row_flatness,
    snap_to_gutters,
)
from .quality import (
    DiagramQuality,
    background_score,
    contrast_score,
    gutter_score,
    ink_fraction,
    ink_score,
    rank_diagrams,
    score_diagram,
    separator_count,
)
from .score import (
    CandidateScore,
    change_outside,
    context_drift,
    rank,
    score_candidate,
    seam_discontinuity,
)

__all__ = [
    "GALLERY_EDGE",
    "VIEWER_EDGE",
    "CandidateScore",
    "DiagramQuality",
    "CompositeInvariantError",
    "DEFAULT_TOLERANCE",
    "Derivative",
    "Exported",
    "Rect",
    "RegionPlan",
    "RegionResult",
    "align",
    "apply_gain_offset",
    "apply_region_edit",
    "assert_outside_unchanged",
    "FLAT_BACKGROUND_SPREAD",
    "background_mask",
    "background_spread",
    "has_flat_background",
    "build_pyramid",
    "change_outside",
    "choose_best",
    "column_flatness",
    "composite",
    "context_drift",
    "encode",
    "estimate_shift",
    "export",
    "expand_to_legal",
    "feather_mask",
    "fit_gain_offset",
    "flat_runs",
    "gutter_fraction",
    "make_transparent",
    "normalise",
    "outside_difference",
    "plan_region_edit",
    "rank",
    "background_score",
    "contrast_score",
    "gutter_score",
    "ink_fraction",
    "ink_score",
    "rank_diagrams",
    "score_diagram",
    "separator_count",
    "residual",
    "row_flatness",
    "score_candidate",
    "seam_discontinuity",
    "shift_image",
    "snap_to_gutters",
    "to_array",
    "to_png",
    "upscale",
]
